apiVersion: apps/v1
kind: Deployment
metadata:
  name: creacion-agente-mcp
  labels:
    app: creacion-agente-mcp
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creacion-agente-mcp
  template:
    metadata:
      labels:
        app: creacion-agente-mcp
        version: v1
    spec:
      containers:
      - name: mcp-server
        image: creacion-agente-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: health
          protocol: TCP
        env:
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: api-key
        - name: AZURE_OPENAI_API_VERSION
          value: "2024-02-15-preview"
        - name: HEALTH_CHECK_PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
