apiVersion: v1
kind: Service
metadata:
  name: creacion-agente-mcp
  labels:
    app: creacion-agente-mcp
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: health
  selector:
    app: creacion-agente-mcp
